# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Input: s = "", t = "y"
# Output: "y"

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        code = 0
        
        for ch in t:
            code += ord(ch)

        for ch in s:
           code -= ord(ch)

        return chr(code)
    
solution = Solution()
print(solution.findTheDifference("abcd", "abcde"))
print(solution.findTheDifference("", "y"))